#!/bin/bash
# Auto-generated sub-interface configuration script
# Generated by configure_vrf_subinterfaces.py

# Create VRF Vrf1
config vrf add Vrf1

# Create VRF Vrf2
config vrf add Vrf2

# Create VRF Vrf3
config vrf add Vrf3

# Configure PortChannel1.100
config subinterface add PortChannel1.100 100
config interface vrf bind PortChannel1.100 Vrf1
config interface ip add PortChannel1.100 10.10.0.1/31
config interface ip add PortChannel1.100 fc00:a:a::1/127
config interface startup PortChannel1.100

# Configure PortChannel1.101
config subinterface add PortChannel1.101 101
config interface vrf bind PortChannel1.101 Vrf2
config interface ip add PortChannel1.101 10.10.0.3/31
config interface ip add PortChannel1.101 fc00:a:a::3/127
config interface startup PortChannel1.101

# Configure PortChannel1.102
config subinterface add PortChannel1.102 102
config interface vrf bind PortChannel1.102 Vrf3
config interface ip add PortChannel1.102 10.10.0.5/31
config interface ip add PortChannel1.102 fc00:a:a::5/127
config interface startup PortChannel1.102

# Configure PortChannel2.100
config subinterface add PortChannel2.100 100
config interface vrf bind PortChannel2.100 Vrf1
config interface ip add PortChannel2.100 10.10.1.1/31
config interface ip add PortChannel2.100 fc00:a:a:1::1/127
config interface startup PortChannel2.100

# Configure PortChannel2.101
config subinterface add PortChannel2.101 101
config interface vrf bind PortChannel2.101 Vrf2
config interface ip add PortChannel2.101 10.10.1.3/31
config interface ip add PortChannel2.101 fc00:a:a:1::3/127
config interface startup PortChannel2.101

# Configure PortChannel2.102
config subinterface add PortChannel2.102 102
config interface vrf bind PortChannel2.102 Vrf3
config interface ip add PortChannel2.102 10.10.1.5/31
config interface ip add PortChannel2.102 fc00:a:a:1::5/127
config interface startup PortChannel2.102
