#!/bin/bash
# Auto-generated sub-interface configuration script
# Generated by configure_vrf_subinterfaces.py

# Create VRF ISP1
config vrf add ISP1

# Create VRF ISP2
config vrf add ISP2

# Create VRF ISP3
config vrf add ISP3

# Configure Ethernet0.100
config subinterface add Ethernet0.100 100
config interface vrf bind Ethernet0.100 ISP1
config interface ip add Ethernet0.100 192.168.1.0/31
config interface startup Ethernet0.100

# Configure Ethernet0.101
config subinterface add Ethernet0.101 101
config interface vrf bind Ethernet0.101 ISP2
config interface ip add Ethernet0.101 192.168.1.2/31
config interface startup Ethernet0.101

# Configure Ethernet0.102
config subinterface add Ethernet0.102 102
config interface vrf bind Ethernet0.102 ISP3
config interface ip add Ethernet0.102 192.168.1.4/31
config interface startup Ethernet0.102
