#!/bin/bash
# Auto-generated sub-interface removal script
# Generated by configure_vrf_subinterfaces.py

# Remove PortChannel2.102
config interface ip remove PortChannel2.102 10.10.1.5/31
config interface ip remove PortChannel2.102 fc00:a:a:1::5/127
config interface vrf unbind PortChannel2.102
config subinterface del PortChannel2.102

# Remove PortChannel2.101
config interface ip remove PortChannel2.101 10.10.1.3/31
config interface ip remove PortChannel2.101 fc00:a:a:1::3/127
config interface vrf unbind PortChannel2.101
config subinterface del PortChannel2.101

# Remove PortChannel2.100
config interface ip remove PortChannel2.100 10.10.1.1/31
config interface ip remove PortChannel2.100 fc00:a:a:1::1/127
config interface vrf unbind PortChannel2.100
config subinterface del PortChannel2.100

# Remove PortChannel1.102
config interface ip remove PortChannel1.102 10.10.0.5/31
config interface ip remove PortChannel1.102 fc00:a:a::5/127
config interface vrf unbind PortChannel1.102
config subinterface del PortChannel1.102

# Remove PortChannel1.101
config interface ip remove PortChannel1.101 10.10.0.3/31
config interface ip remove PortChannel1.101 fc00:a:a::3/127
config interface vrf unbind PortChannel1.101
config subinterface del PortChannel1.101

# Remove PortChannel1.100
config interface ip remove PortChannel1.100 10.10.0.1/31
config interface ip remove PortChannel1.100 fc00:a:a::1/127
config interface vrf unbind PortChannel1.100
config subinterface del PortChannel1.100

# Remove VRF Vrf3
config vrf del Vrf3

# Remove VRF Vrf2
config vrf del Vrf2

# Remove VRF Vrf1
config vrf del Vrf1
