#!/bin/bash
# Auto-generated sub-interface removal script
# Generated by configure_vrf_subinterfaces.py

# Remove Po4.103
config interface ip remove Po4.103 10.10.20.38/31
config interface ip remove Po4.103 fc00:a:a:14::26/127
config interface vrf unbind Po4.103
config subinterface del Po4.103

# Remove Po4.102
config interface ip remove Po4.102 10.10.20.36/31
config interface ip remove Po4.102 fc00:a:a:14::24/127
config interface vrf unbind Po4.102
config subinterface del Po4.102

# Remove Po4.101
config interface ip remove Po4.101 10.10.20.34/31
config interface ip remove Po4.101 fc00:a:a:14::22/127
config interface vrf unbind Po4.101
config subinterface del Po4.101

# Remove Po4.100
config interface ip remove Po4.100 10.10.20.32/31
config interface ip remove Po4.100 fc00:a:a:14::20/127
config interface vrf unbind Po4.100
config subinterface del Po4.100

# Remove Po3.103
config interface ip remove Po3.103 10.10.20.30/31
config interface ip remove Po3.103 fc00:a:a:14::1e/127
config interface vrf unbind Po3.103
config subinterface del Po3.103

# Remove Po3.102
config interface ip remove Po3.102 10.10.20.28/31
config interface ip remove Po3.102 fc00:a:a:14::1c/127
config interface vrf unbind Po3.102
config subinterface del Po3.102

# Remove Po3.101
config interface ip remove Po3.101 10.10.20.26/31
config interface ip remove Po3.101 fc00:a:a:14::1a/127
config interface vrf unbind Po3.101
config subinterface del Po3.101

# Remove Po3.100
config interface ip remove Po3.100 10.10.20.24/31
config interface ip remove Po3.100 fc00:a:a:14::18/127
config interface vrf unbind Po3.100
config subinterface del Po3.100

# Remove Po2.103
config interface ip remove Po2.103 10.10.20.22/31
config interface ip remove Po2.103 fc00:a:a:14::16/127
config interface vrf unbind Po2.103
config subinterface del Po2.103

# Remove Po2.102
config interface ip remove Po2.102 10.10.20.20/31
config interface ip remove Po2.102 fc00:a:a:14::14/127
config interface vrf unbind Po2.102
config subinterface del Po2.102

# Remove Po2.101
config interface ip remove Po2.101 10.10.20.18/31
config interface ip remove Po2.101 fc00:a:a:14::12/127
config interface vrf unbind Po2.101
config subinterface del Po2.101

# Remove Po2.100
config interface ip remove Po2.100 10.10.20.16/31
config interface ip remove Po2.100 fc00:a:a:14::10/127
config interface vrf unbind Po2.100
config subinterface del Po2.100

# Remove Po1.103
config interface ip remove Po1.103 10.10.20.14/31
config interface ip remove Po1.103 fc00:a:a:14::e/127
config interface vrf unbind Po1.103
config subinterface del Po1.103

# Remove Po1.102
config interface ip remove Po1.102 10.10.20.12/31
config interface ip remove Po1.102 fc00:a:a:14::c/127
config interface vrf unbind Po1.102
config subinterface del Po1.102

# Remove Po1.101
config interface ip remove Po1.101 10.10.20.10/31
config interface ip remove Po1.101 fc00:a:a:14::a/127
config interface vrf unbind Po1.101
config subinterface del Po1.101

# Remove Po1.100
config interface ip remove Po1.100 10.10.20.8/31
config interface ip remove Po1.100 fc00:a:a:14::8/127
config interface vrf unbind Po1.100
config subinterface del Po1.100

# Remove VRF Vrf4
config vrf del Vrf4

# Remove VRF Vrf3
config vrf del Vrf3

# Remove VRF Vrf2
config vrf del Vrf2

# Remove VRF Vrf1
config vrf del Vrf1
